version: '3.8'
services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - '5000:5000'
    links:
      - mongo
  client:
    tty: true
    container_name: client
    restart: on-failure
    build: ./client
    ports:
      - '3000:3000'
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    working_dir: /data
    ports:
      - '2717:27017'
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
